lang: zh
minified_css:
  - classic-base.css
  - classic-buttons.css
dest:
  - dir: guide-page
    name: index.html
    reg: ldtstore.com.cn
  - dir: guide-page-intl
    name: index.html
    reg: none
